services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123!!
      - IBM_MQ_HOST=ibmmq # Updated to match the IBM MQ service name
      - IBM_MQ_PORT=1414
      - IBM_MQ_QUEUE_MANAGER=QM1
      - IBM_MQ_CHANNEL=DEV.APP.SVRCONN
      - IBM_MQ_USERNAME=app
      - IBM_MQ_PASSWORD=passw0rd
      - IBM_MQ_QUEUE=DEV.QUEUE.1
    depends_on:
      - db
      - ibmmq

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_PASSWORD=123!!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ibmmq:
    image: ibmcom/mq:9.2.4.0-r1
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=passw0rd
    volumes:
      - qmdata:/mnt/mqm

volumes:
  postgres_data:
  qmdata:
